// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	healthCheck: () => typedError<HealthStatus, AppError>(__TAURI_INVOKE("health_check")),
	conversationList: () => typedError<ConversationDto[], AppError>(__TAURI_INVOKE("conversation_list")),
	conversationGet: (id: string) => typedError<ConversationDto, AppError>(__TAURI_INVOKE("conversation_get", { id })),
	conversationCreate: (request: CreateConversationRequest) => typedError<ConversationDto, AppError>(__TAURI_INVOKE("conversation_create", { request })),
	conversationUpdate: (request: UpdateConversationRequest) => typedError<ConversationDto, AppError>(__TAURI_INVOKE("conversation_update", { request })),
	conversationDelete: (request: DeleteConversationRequest) => typedError<null, AppError>(__TAURI_INVOKE("conversation_delete", { request })),
	providerProfileList: () => typedError<ProviderProfilesDto, AppError>(__TAURI_INVOKE("provider_profile_list")),
	providerProfileReload: () => typedError<ProviderProfilesDto, AppError>(__TAURI_INVOKE("provider_profile_reload")),
	providerProfileCreate: (request: CreateProviderProfileRequest) => typedError<ProviderProfilesDto, AppError>(__TAURI_INVOKE("provider_profile_create", { request })),
	providerProfileUpdate: (request: UpdateProviderProfileRequest) => typedError<ProviderProfilesDto, AppError>(__TAURI_INVOKE("provider_profile_update", { request })),
	providerProfileDelete: (providerId: string) => typedError<ProviderProfilesDto, AppError>(__TAURI_INVOKE("provider_profile_delete", { providerId })),
	providerProfileSetDefault: (providerId: string) => typedError<ProviderProfilesDto, AppError>(__TAURI_INVOKE("provider_profile_set_default", { providerId })),
	providerModelSync: (providerId: string) => typedError<ProviderProfilesDto, AppError>(__TAURI_INVOKE("provider_model_sync", { providerId })),
	settingsGet: () => typedError<SettingsSnapshotDto, AppError>(__TAURI_INVOKE("settings_get")),
	settingsUpdate: (request: UpdateSettingsRequest) => typedError<SettingsSnapshotDto, AppError>(__TAURI_INVOKE("settings_update", { request })),
	credentialStatusList: () => typedError<CredentialStatusDto[], AppError>(__TAURI_INVOKE("credential_status_list")),
	credentialSet: (request: SetCredentialRequest) => typedError<CredentialStatusDto, AppError>(__TAURI_INVOKE("credential_set", { request })),
	credentialDelete: (providerId: string) => typedError<CredentialStatusDto, AppError>(__TAURI_INVOKE("credential_delete", { providerId })),
	attachmentList: (conversationId: string) => typedError<AttachmentDto[], AppError>(__TAURI_INVOKE("attachment_list", { conversationId })),
	attachmentPickAndImport: (conversationId: string) => typedError<{
	id: string,
	conversationId: string,
	mediaType: string,
	fileName: string,
	byteLength: string,
	contentHash: string,
	createdAtMs: string,
} | null, AppError>(__TAURI_INVOKE("attachment_pick_and_import", { conversationId })),
	attachmentDelete: (id: string) => typedError<null, AppError>(__TAURI_INVOKE("attachment_delete", { id })),
	chatStart: (request: ChatStartRequest) => typedError<ChatStartResponse, AppError>(__TAURI_INVOKE("chat_start", { request })),
	chatCancel: (runId: string) => typedError<null, AppError>(__TAURI_INVOKE("chat_cancel", { runId })),
	chatPause: (runId: string) => typedError<null, AppError>(__TAURI_INVOKE("chat_pause", { runId })),
	chatResume: (request: ChatResumeRequest) => typedError<ChatStartResponse, AppError>(__TAURI_INVOKE("chat_resume", { request })),
	chatInput: (request: ChatInputRequest) => typedError<null, AppError>(__TAURI_INVOKE("chat_input", { request })),
	chatSnapshot: (conversationId: string) => typedError<ChatSnapshotDto, AppError>(__TAURI_INVOKE("chat_snapshot", { conversationId })),
};

/* Types */
export type ActiveRunDto = {
	id: string,
	status: RunStatus,
	phase: RunPhase,
	lastEventSeq: string,
	stopReason: string | null,
	canResume: boolean,
};

export type AppError = { code: "INVALID_INPUT"; message: string } | { code: "NOT_FOUND"; message: string } | { code: "CONFLICT"; message: string } | { code: "STORAGE"; message: string } | { code: "CONFIGURATION"; message: string } | { code: "INTERNAL"; message: string };

export type AppSettings = {
	requestTimeoutSeconds: number,
	maxModelSteps: number,
	attachmentMaxMegabytes: number,
	defaultStrategy: RunStrategy,
	theme?: ThemePreference,
};

export type AttachmentDto = {
	id: string,
	conversationId: string,
	mediaType: string,
	fileName: string,
	byteLength: string,
	contentHash: string,
	createdAtMs: string,
};

export type ChatInputRequest = {
	runId: string,
	intent: PendingInputIntent,
	text: string,
};

export type ChatResumeRequest = {
	runId: string,
	conversationId: string,
};

export type ChatSnapshotDto = {
	conversationId: string,
	activeRun: ActiveRunDto | null,
	items: RunItemDto[],
	events: RunEventDto[],
	toolExecutions: ToolExecutionDto[],
	pendingInputs: PendingInputDto[],
};

export type ChatStartRequest = {
	conversationId: string,
	text: string,
	attachmentIds: string[],
	replacesRunId: string | null,
};

export type ChatStartResponse = {
	runId: string,
};

export type ConversationDto = {
	id: string,
	title: string,
	defaultProviderProfileId: string,
	defaultModel: string,
	version: number,
	createdAtMs: string,
	updatedAtMs: string,
};

export type CreateConversationRequest = {
	title: string,
	providerProfileId: string | null,
	model: string | null,
};

export type CreateProviderProfileRequest = {
	id: string,
	label: string,
	kind: ProviderKind,
	protocol: ProviderProtocol,
	baseUrl: string,
	defaultModel: string,
	storeResponses: boolean,
	capabilities: ProviderCapabilitiesDto,
};

export type CredentialStatusDto = {
	providerId: string,
	configured: boolean,
};

export type DeleteConversationRequest = {
	id: string,
	expectedVersion: number,
};

export type HealthStatus = {
	appName: string,
	appVersion: string,
	platform: string,
	phase: string,
};

export type PendingInputDto = {
	id: string,
	runId: string,
	intent: PendingInputIntent,
	status: string,
	text: string,
};

export type PendingInputIntent = "append" | "fork" | "cancel_and_replace";

export type ProviderCapabilitiesDto = {
	tools: boolean,
	images: boolean,
	files: boolean,
};

export type ProviderKind = "openai_responses" | "openai_compatible";

export type ProviderProfileDto = {
	id: string,
	label: string,
	kind: string,
	protocol: string,
	baseUrl: string,
	defaultModel: string,
	availableModels: string[],
	enabledModels: string[],
	modelsSyncedAtMs: string | null,
	storeResponses: boolean,
	capabilities: ProviderCapabilitiesDto,
};

export type ProviderProfilesDto = {
	configPath: string,
	defaultProviderId: string,
	profiles: ProviderProfileDto[],
};

export type ProviderProtocol = "responses" | "chat_completions";

export type RunEventDto = {
	runId: string,
	seq: string,
	kind: string,
	payloadJson: string,
	persistedAtMs: string,
};

export type RunItemDto = {
	id: string,
	runId: string,
	seq: string,
	kind: string,
	role: string | null,
	contentJson: string,
	callId: string | null,
	createdAtMs: string,
};

export type RunPhase = "routing" | "planning" | "model_stream" | "tool_prepare" | "tool_execute" | "observation_commit" | "reflecting" | "finalizing" | "none";

export type RunStatus = "queued" | "running" | "pause_requested" | "paused" | "suspended" | "waiting_for_approval" | "completed" | "failed" | "cancelled" | "interrupted" | "recovery_required";

export type RunStrategy = "fast" | "auto" | "quality";

export type SetCredentialRequest = {
	providerId: string,
	secret: string,
};

export type SettingsSnapshotDto = {
	settings: AppSettings,
	settingsPath: string,
	databasePath: string,
	attachmentPath: string,
};

export type ThemePreference = "system" | "light" | "dark";

export type ToolExecutionDto = {
	id: string,
	runId: string,
	callId: string,
	toolName: string,
	status: string,
	risk: string,
	argumentsJson: string,
	outputJson: string | null,
	errorMessage: string | null,
};

export type UpdateConversationRequest = {
	id: string,
	expectedVersion: number,
	title: string | null,
	defaultProviderProfileId: string | null,
	defaultModel: string | null,
};

export type UpdateProviderProfileRequest = {
	id: string,
	label: string,
	baseUrl: string,
	defaultModel: string,
	enabledModels: string[],
	storeResponses: boolean,
	capabilities: ProviderCapabilitiesDto,
};

export type UpdateSettingsRequest = {
	settings: AppSettings,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

