// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	healthCheck: () => typedError<HealthStatus, AppError>(__TAURI_INVOKE("health_check")),
};

/* Types */
export type AppError = { code: "INTERNAL"; message: string };

export type HealthStatus = {
	appName: string,
	appVersion: string,
	platform: string,
	phase: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

